### ISSUE TITLE
Broken in VS Code

### ISSUE THREAD

**Issue by raysuelzer** [microsoft/node-spdlog#29]
It looks like perhaps some changes here broke VS Code. Perhaps related to how this is being built not on yarn anymore? I'm not sure, but the library is not being compiled correctly anymore and is missing symbols. I notice changes to the install script 
```
Error relocating /root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/node_modules/spdlog/build/Release/spdlog.node: _ZSt28__throw_bad_array_new_lengthv: symbol not found
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1187:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.m._load (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/workbench/api/node/extensionHostProcess.js:125:14199)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/node_modules/spdlog/index.js:3:35)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.m._load (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/workbench/api/node/extensionHostProcess.js:125:14199)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at i (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/loader.js:5:98)
    at n.load (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/loader.js:4:1651)
    at _.load (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/loader.js:3:9105)
    at u (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/loader.js:5:9325)
    at Object.errorback (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/loader.js:5:9444)
    at _.triggerErrorback (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/loader.js:3:9399)
    at /root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/loader.js:3:9150
    at n.load (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/loader.js:4:1668)
    at _.load (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/loader.js:3:9105)
    at u (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/loader.js:5:9325)
    at h._loadModule (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/loader.js:5:9453)
    at h._resolve (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/loader.js:6:452)
    at h.defineModule (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/loader.js:5:5548)
    at h._relativeRequire (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/loader.js:5:6172)
    at e (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/loader.js:5:8503)
    at R.C (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/workbench/api/node/extensionHostProcess.js:88:8815)
    at new Promise (<anonymous>)
    at R (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/workbench/api/node/extensionHostProcess.js:88:8795)
    at D.n (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/workbench/api/node/extensionHostProcess.js:88:9925)
    at new D (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/workbench/api/node/extensionHostProcess.js:88:9795)
    at P.m (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/workbench/api/node/extensionHostProcess.js:106:954)
    at P.createLogger (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/workbench/api/node/extensionHostProcess.js:88:5469)
    at new P (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/workbench/api/node/extensionHostProcess.js:91:13841)
    at S.j (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/workbench/api/node/extensionHostProcess.js:84:1296)
    at /root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/workbench/api/node/extensionHostProcess.js:84:3032
    at z.a (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/workbench/api/node/extensionHostProcess.js:66:48073)
    at z.get value [as value] (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/workbench/api/node/extensionHostProcess.js:66:48227)
    at Object.get (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/workbench/api/node/extensionHostProcess.js:84:3438)
    at new u (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/workbench/api/node/extensionHostProcess.js:115:1150)
    at c (/root/.vscode-server-insiders/bin/f31dffc7f9b93a1cdef21243ec30dea7d489a615-insider/out/vs/workbench/api/node/extensionHostProcess.js:125:18641)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

https://github.com/microsoft/vscode/issues/178748#issuecomment-1492032594

**Comment by deepak1556** [comment]
Upstream issue has been resolved, closing.
